name: "CI (Integração Contínua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN:

on:
  pull_request: 
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runs Installation
        run: yarn install
      - name: Run Linter
        run: yarn lint

  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runs Installation
        run: yarn install
      - name: Run Preview Deployment
        run: yarn deploy:preview